### ISSUE TITLE
連結無效 404

### ISSUE THREAD

**Issue by ysya** [ECPay/ECPayPHPCartModule#3]
ECPay_WooCommerce_v1.0.0921.zip 不支援電子發票自動開立版本

ECPay_WooCommerce_v1.0.10222.zip 支援電子發票自動開立版本

此兩檔案連結皆為 404，請確認看看

payment/ 中也無此二檔案

**Comment by AllennChang** [comment]
不好意思,已完作上版動作,請在試試,感謝
