### ISSUE TITLE
信用卡操作失敗

### ISSUE THREAD

**Issue by cuiian** [ECPay/ECPayPHPCartModule#4]
買家使用信用卡刷卡款項有正常收到
不過購物車模組回傳資料給我的網站操作失敗的訊息
請查明原因一下 謝謝
截圖:
http://i.imgur.com/Dzga0El.png

**Comment by AllennChang** [comment]
感謝您的反應,相關系統錯誤問題請連絡我們客服人員 ,
https://www.ecpay.com.tw/ServiceReply/Create
