### ISSUE TITLE
超商代碼繳費資訊

### ISSUE THREAD

**Issue by cuiian** [ECPay/ECPayPHPCartModule#5]
我在其他網站看到用你們的超商代碼繳費
在取得代碼後ECShop訂單裡會有完整的資訊
包括繳費代碼及繳費期限 如連結截圖1
不過我裝上去沒有這些資訊 如截圖2
本來猜想是網站經營者自己客製的
不過看到幾個網站的畫面排版配色等等都一模一樣
在想是不是你們哪個版本的模組有這個功能?

截圖1. http://imgur.com/a/a4jvS
截圖2. http://imgur.com/a/ljRWf

**Comment by AllennChang** [comment]
感謝您的反應,相關系統錯誤問題請連絡我們客服人員 ,
https://www.ecpay.com.tw/ServiceReply/Create
